excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://whitedreams.github.io
title: Awesome
email: 
author: whitedreams
description: My awesome new site
paginate: 3
google_analytics: 